name: Sanity check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled

jobs:
  pr_wip_check:
    runs-on: ubuntu-latest
    name: WIP Check
    steps:
    - name: WIP Check
      uses: tim-actions/wip-check@master
      with:
        labels: '["skip_sonar"]'
        keywords: '["skip_sonar"]'
